### ISSUE TITLE
pi 3b

### ISSUE THREAD

**Issue by jschoch** [scottalford75/Remora#20]
i have an extra 3b and 4b's are hard to find.  Is it viable to use a 3b still with Remora?  Any guides to getting it up and running that are current?

**Comment by scottalford75** [comment]
Yes, it's still possible to use 3b's with Remora. I've got two installs still running with them. They are fine for "smaller" g-code files. When I say smaller, they will still load a 1,000,000 line file but the Axis GUI gets slow. Program runs fine.

The docs are up to date: https://remora-docs.readthedocs.io/en/latest/index.html
