### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jrstrick** [scottalford75/Remora#27]
Just a quick question on the TMC2208 driver support in Remora. Does Remora use the step/direction pins for stepping and direction even when a UART RX line is enabled for the TMC2208?

**Comment by scottalford75** [comment]
Correct. The UART connection is used for the configuration of the driver. Once setup the module shuts down the UART connection and the driver uses the step and direction pins.

I have tested velocity mode with the drivers, but this is not implemented in Remora. In this mode the driver velocity and direction is instructed over the serial connection.

**Comment by jrstrick** [comment]
Good to know, thanks.
