### ISSUE TITLE
Question 2

### ISSUE THREAD

**Issue by BinaryMirko** [scottalford75/Remora#31]
Hi Scott, i have a "simple" question: is it possible to run the Remora firmware on e.g. ATSAM4E16E controllers(I'm a Duet Fan ^^) and would the port be very complicated/time consuming?

**Comment by scottalford75** [comment]
Hi, anything is possible, it's just the time and effort required. As the Duet uses an Atmel micro all of the low level code would need to be re-written. That said they are both Cortex based ARM processors so it may not be two difficult if you would like to give it a go.
