### ISSUE TITLE
Request for support for STM32F405

### ISSUE THREAD

**Issue by dmason1992** [scottalford75/Remora#34]
Hi,

The Mellow Fly Gemini board (https://s.click.aliexpress.com/e/_DDNALgT) Is a hybrid linux SBC and printer controller board. I think it's the perfect candidate for a linux CNC implementation for low cost low power CNC machines.

It uses the STM32F405 so I am asking for support for this chip.

**Comment by scottalford75** [comment]
Hi the STM32F407 code should / will run on the 405.

**Comment by dmason1992** [comment]
I will test this out when my board arrives :)
