### ISSUE TITLE
Little Bug in SKR2 Config Sample

### ISSUE THREAD

**Issue by jowa01** [scottalford75/Remora#47]
Hi,
i am new to linux and linuxcnc.
Hardware Pi3b + SKR2
The first challenge, install on Pi3b.
The second challenge, connect with SKR2.
I found the problem in the Sample config for the SKR2.
For "Temperature" the Pin must be PA_2
For "RCServo" the Pin must be PE_5

Best regards.
Joachim

**Comment by cakeslob** [comment]
Thank you, It is fixed in other branch that will be merged with main soon
https://github.com/scottalford75/Remora/blob/develop/Firmware/ConfigSamples/SKRv2_ender3/config.txt
