### ISSUE TITLE
TMC5160 support

### ISSUE THREAD

**Issue by joaobarros** [scottalford75/Remora#55]
@cakeslob

Any update on your effort to support the 5160s (and more models)?

I see you reverted your initial commit: https://github.com/scottalford75/Remora/commit/1d37aded962142a7bbc77539eca128c7c3025014

Do you need any testing? I have the hardware.

**Comment by cakeslob** [comment]
It was suppossed to be a separate branch for community dev as a starting point, but it got mixed into a pull request by accident. It doesnt work yet
