### ISSUE TITLE
SKR V1.4 Turbo or LPC1769

### ISSUE THREAD

**Issue by hcremer** [scottalford75/Remora#58]
Hello,

I saw that there are 2 firmwares one called "SKR V1.4 Turbo" (one year old) and one called "LPC1769" (9 months old).
Which one is the best for the BIGTREETECH SKR V1.4 / Turbo?

Best regards,
beamer

**Comment by cakeslob** [comment]
they are probably the same, but SKR1.4 turbo was supposed to be deleted after a restructuring. it was renamed LPC1769

use the lpc one

**Comment by hcremer** [comment]
Thank you very much and happy holydays :-)
