### ISSUE TITLE
SKR E3 Turbo support

### ISSUE THREAD

**Issue by zmrdko** [scottalford75/Remora#59]
Hi Scott,
would it be possible to add support for SKR E3 Turbo with little effort? It has the same LPC1769 as SKR 1.4 Turbo.
Im just not sure if it would be possible to wire it to rasberry pi:

https://teamgloomy.github.io/skr_E3T_pins.html

There is no EXP2 connector and I did not find pin 1.31.

**Comment by cakeslob** [comment]
1.31 is the reset pin, if you need to change it, you just need to adjust your config.txt and change the reset pin number. it looks like the other pins are there, 0.15-0.18 so it should be fine

**Comment by zmrdko** [comment]
one more pin is missing: 3.25 which is allocated for standby mode for Y stepper driver on E3 Turbo. What to do with this one?

**Comment by zmrdko** [comment]
I changed the config acording to pinout for E3 Turbo, but now I'm getting error:
```
Testing connection to TMC driver...failed!
Likely cause: no power
  Fix the problem and reset board.
```
[log.txt](https://github.com/scottalford75/Remora/files/13798471/log.txt)

**Comment by cakeslob** [comment]
Hey, sorry I must have missed this post, do you have it working now? It looks like your 2209's are not communicating with remora, but I am not an expert with the LPC or TMC drivers
