### ISSUE TITLE
Would it be possible to use ethernet-to-spi or serial-to-spi adapters?

### ISSUE THREAD

**Issue by ipsod** [scottalford75/Remora#60]
In order to run Remora on any PC, using a 3d printer board, would it be possible to use ethernet-to-spi or serial-to-spi adapters?

**Comment by scottalford75** [comment]
Yes, and there is active work in this area using a W5500 Ethernet module.

https://www.forum.linuxcnc.org/18-computer/42276-remora-rpi-software-stepping-using-external-microcontroller-via-spi?start=760#290252

**Comment by cakeslob** [comment]
Yeah, we have a thing going on here
https://github.com/cakeslob/Remora-STM32F4xx-W5500/tree/nucleo_2
